// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://zwoqzptpoekzwracicbm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp3b3F6cHRwb2VrendyYWNpY2JtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA3MDg2MjMsImV4cCI6MjA4NjI4NDYyM30.REj0u5ThCVAXy44udtiO1SLa6-rZwjHgXonncs7qbIE";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);